feature:
  - head-branch: ['feature/*', 'feat/*']

bug:
  - head-branch: ['bugfix/*', 'bug/*', 'fix/*']

docs:
  - head-branch: ['docs/*', 'documentation/*']

chore:
  - head-branch: ['chore/*', 'maintenance/*']
